"""Add release_name to deployments

Revision ID: 1b79722b52cf
Revises: 2dbf36af55aa
Create Date: 2024-06-15 21:06:19.777935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b79722b52cf'
down_revision: Union[str, None] = '2dbf36af55aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('release_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_deployments_release_name'), 'deployments', ['release_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_release_name'), table_name='deployments')
    op.drop_column('deployments', 'release_name')
    # ### end Alembic commands ###
