"""Add status column to Deployment

Revision ID: 2dbf36af55aa
Revises: a64ec9002f40
Create Date: 2024-06-15 19:28:32.164220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbf36af55aa'
down_revision: Union[str, None] = 'a64ec9002f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'status')
    # ### end Alembic commands ###
