"""create the namespace if it does not exist

Revision ID: 344de7babc52
Revises: 85c5a99f3adc
Create Date: 2024-06-15 18:08:57.503493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344de7babc52'
down_revision: Union[str, None] = '85c5a99f3adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
