"""Create helm_repositories table

Revision ID: 528016d531f2
Revises: 8ee738ee491d
Create Date: 2024-06-15 22:19:29.585506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528016d531f2'
down_revision: Union[str, None] = '8ee738ee491d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helm_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helm_repositories_id'), 'helm_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_helm_repositories_name'), 'helm_repositories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helm_repositories_name'), table_name='helm_repositories')
    op.drop_index(op.f('ix_helm_repositories_id'), table_name='helm_repositories')
    op.drop_table('helm_repositories')
    # ### end Alembic commands ###
