"""Add foreign key constraint between Namespace and Deployment

Revision ID: 85c5a99f3adc
Revises: 93a0fa221549
Create Date: 2024-06-15 18:02:37.668762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c5a99f3adc'
down_revision: Union[str, None] = '93a0fa221549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('namespace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deployments', 'namespaces', ['namespace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'namespace_id')
    # ### end Alembic commands ###
