"""Rename release_type to project in Deployment model

Revision ID: 93a0fa221549
Revises: c86f2758062c
Create Date: 2024-06-15 17:51:54.396911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a0fa221549'
down_revision: Union[str, None] = 'c86f2758062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('project', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('namespace_name', sa.String(), nullable=True))
    op.drop_index('ix_deployments_release_type', table_name='deployments')
    op.create_index(op.f('ix_deployments_namespace_name'), 'deployments', ['namespace_name'], unique=False)
    op.create_index(op.f('ix_deployments_project'), 'deployments', ['project'], unique=False)
    op.drop_constraint('deployments_namespace_id_fkey', 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'release_type')
    op.drop_column('deployments', 'namespace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('namespace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('release_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('deployments_namespace_id_fkey', 'deployments', 'namespaces', ['namespace_id'], ['id'])
    op.drop_index(op.f('ix_deployments_project'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_namespace_name'), table_name='deployments')
    op.create_index('ix_deployments_release_type', 'deployments', ['release_type'], unique=False)
    op.drop_column('deployments', 'namespace_name')
    op.drop_column('deployments', 'project')
    # ### end Alembic commands ###
