"""Add active column to Deployment

Revision ID: a64ec9002f40
Revises: d5ff35b77e2b
Create Date: 2024-06-15 19:03:13.432263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64ec9002f40'
down_revision: Union[str, None] = 'd5ff35b77e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'active')
    # ### end Alembic commands ###
