"""Add namespace_name and values columns to Deployment

Revision ID: b3d14a655a7f
Revises: 344de7babc52
Create Date: 2024-06-15 18:35:09.848994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d14a655a7f'
down_revision: Union[str, None] = '344de7babc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('values', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'values')
    # ### end Alembic commands ###
