"""Add revision column to Deployment

Revision ID: d5ff35b77e2b
Revises: b3d14a655a7f
Create Date: 2024-06-15 18:45:25.406462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ff35b77e2b'
down_revision: Union[str, None] = 'b3d14a655a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('revision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'revision')
    # ### end Alembic commands ###
